#!/usr/bin/env bash
#Write a Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.
count=0
while [ $count = 10 ]
do
	((count++))
	echo "Best School"
if
	[[ "$count" == '9' ]]; then
	continue
fi
echo 'Hi'
done
